/*
 * PI Web API 2017 Swagger Spec
 * Swagger Spec file that describes PI Web API
 *
 * OpenAPI spec version: 1.9.0.235
 * Contact: techsupport@osisoft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.osisoft.pidevclub.piwebapi.auth;

public enum OAuthFlow {
    accessCode, implicit, password, application
}
